books/urls.py
from django.urls import path
from .views import (
    Index,
    BookDetailView,
    CreateBookView,
    UpdateBookView,
    DeleteBookView,
    BookListAllView)

app_name = 'books'

urlpatterns = [
    path('', Index.as_view(), name='home'),
    path('books/', BookListAllView.as_view(), name='list-book'),
    path('create/', CreateBookView.as_view(), name='create-book'),
    path('update/<int:id>', UpdateBookView.as_view(), name='update-book'),
    path('delete/<int:id>', DeleteBookView.as_view(), name='delete-book'),
    path('<slug:slug>/', BookDetailView.as_view(), name='book-detail'),


]

bookstore/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
]

books/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.urls import reverse
from django import forms
# Create your models here.


class Author(models.Model):
    name = models.CharField(max_length=250)
    lastname = models.CharField(max_length=250)


class Books(models.Model):
    GENRES_CHOICES = (
        ("1", "Literatura de ficção"),
        ("2", "Poesia"),
        ("3", "Quadrinhos"),
        ("4", "Livros científicos"),
        ("5", "Religião")
    )

    title = models.CharField(max_length=240)
    author = models.CharField(max_length=240)

    genres = models.CharField(
        max_length=1, choices=GENRES_CHOICES, blank=False, null=False)
    date = models.DateField()
    slug = models.SlugField(null=True)
    created_at = models.DateField(auto_now=True)
    count = models.IntegerField(null=True, default=0)

    def get_absolute_url(self):
        return reverse("books", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super(Books, self).save(*args, **kwargs)

books/forms.py
from django import forms


from .models import Books


class BookModelForm(forms.ModelForm):

    class Meta:
        model = Books
        fields = ["title", 'author', 'genres', 'date']
        widgets = {
            "title": forms.TextInput(attrs={"placeholder": "Book's Title", 'class': "form-control-sm"}),
            "author": forms.TextInput(attrs={"placeholder": "Author's name", 'class': "form-control-sm"}),
            "genres": forms.Select(attrs={'class': "form-control"}),
            'date': forms.DateTimeInput(attrs={'class': "form-control"}),
            # 'slug': forms.TextInput(attrs={'placeholder': 'slugs', 'class': "form-control-sm"})
        }

books/views.py
from django.shortcuts import get_object_or_404, reverse
from django.utils import timezone
from django.db.models import F

from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView)


from books.models import Books
from .forms import BookModelForm

# Create your views here.


class Index(ListView):
    model = Books
    template_name = 'home.html'
    context_object_name = 'books'
    paginate_by = 4


class BookListAllView(ListView):
    model = Books
    template_name = 'books/list-books.html'
    context_object_name = 'books'


class BookDetailView(DetailView):
    model = Books
    template_name = 'book-detail.html'
    #form_class = BookModelForm
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        post = Books.objects.filter(slug=self.kwargs.get('slug'))
        post.update(count=F('count') + 1)

        context['time'] = timezone.now()

        return context


class CreateBookView(CreateView):
    template_name = 'crud/book_create.html'
    form_class = BookModelForm
    queryset = Books.objects.all()
    success_url = '/'

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


class UpdateBookView(UpdateView):
    template_name = 'crud/book_update.html'
    form_class = BookModelForm
    success_url = '/'

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Books, id=id_)

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


class DeleteBookView(DeleteView):
    template_name = 'crud/book_delete.html'
    success_url = '/'

    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Books, id=id_)

books/templates/base.html
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'img/book.ico' %}" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Welcome to Books</title>
</head>

<body>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous">
    </script>
</body>

</html>

books/templates/book-detail.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="max-width:800px">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{book.title}}</h1>
        <div class="d-flex justify-content-between align-items-center">
            <small class="text-muted">{{book.author}}</small>
            <small class="text-muted">{{book.genres}}</small>
            <small class="text-muted">{{book.slug}}</small>
            <small class="text-muted">{{book.date}}</small>
        </div>
    </div>

</div>
{% endblock %}

books/templates/books/list-books.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="max-width:800px">
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Slug</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books  %}
            <tr>

                <td>{{book.title}}</td>
                <td>{{book.author}}</td>
                <td>{{book.slug}}</td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

books/templates/crud/book_create.html
{% extends 'base.html' %}

{% block content %}

<h1>teste</h1>


<form action="." method="POST">
    {% csrf_token %}
    <p> Título: {{form.title}}</p>
    {% comment %} <p> Slug: {{form.slug}}</p> {% endcomment %}
    <p> Autor: {{form.author}}</p>
    <p>Gênero {{form.genres}}</p>
    <p> Data: {{form.date}}</p>


    <input type="submit" value="Create">
</form>

{% endblock content %}

books/templates/crud/book_delete.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    <h1>Você deseja apagar "{{ object.title}}"?</h1>
    <p> <input type="submit" value="Sim" /> <a href="/">Cancelar</a> </p>

</form>

{% endblock %}

books/templates/crud/book_update.html
{% extends 'base.html' %}

{% block content %}

<h1>Update</h1>


<form action="" method="POST">
    {% csrf_token %}
    <p> Título: {{form.title}}</p>
    <p> Slug: {{form.slug}}</p>
    <p> Autor: {{form.author}}</p>
    <p> Gênero {{form.genres}}</p>
    <p> Data: {{form.date}}</p>


    <input type="submit" value="Update">
</form>

{% endblock content %}

books/templates/home.html
   {% extends "base.html" %}
   {% block content %}
   <div class="container">
       <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
           <h1 class="display-4 title-home">All Books</h1>
           <button type="button" class="btn btn-outline-success"><a class="" href="/create">New Book</a></button>
           <button type="button" class="btn btn-outline-success"><a class="" href="/books">List Books</a></button>


           <p class="lead">A range of wonderful programming books to help you learn JavaScript.</p>
       </div>
       <div class="py-5">
           <div class="row">
               {% for book in books %}
               <div class="col-md-4">
                   <a class="text-dark" href="{% url 'books:book-detail' slug=book.slug %}">
                       <div class="card mb-4 box-shadow">
                           <div class="card-body">
                               <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
                                   {{book.title|truncatechars:50}}</h2>
                               <div class="d-flex justify-content-between align-items-center">
                                   <small class="text-muted">{{book.genre}}</small>
                                   <small class="text-muted">{{book.isbn}}</small>
                                   <a href="{% url 'books:update-book' id=book.id %}"> Update Book</a>
                                   <a href="{% url 'books:delete-book' id=book.id %}"> Delete Book</a>
                               </div>
                               <small class=" text-muted">{{time}}</small>
                           </div>
                       </div>
                   </a>
               </div>
               {% endfor %}
           </div>

           <nav aria-label="Page navigation example">
               <ul class="pagination">

                   <li class="page-item">

                       {% if page_obj.has_previous %}
                   <li class="page-item current">
                       <a class="page-link" aria-label="Previous" href="?page={{ page_obj.previous_page_number }}">
                           <span aria-hidden="true">&laquo;
                           </span>
                       </a>
                   </li>
                   {% endif %}

                   <li class="page-item current"><a class="page-link" href="#">{{ page_obj.number }} </a></li>

                   {% if page_obj.has_next %}
                   <li class="page-item current">
                       <a class="page-link" aria-label="Previous" href="?page={{ page_obj.next_page_number }}"><span
                               aria-hidden="true">&raquo;</span></a>
                   </li>
                   {% endif %}
                   </li>
               </ul>
           </nav>
       </div>
       {% endblock %}


       {% comment %}

       <div class="row">
           <div class="col-12">
               <span class="step-">
                   {% if page_obj.has_previous %}
                   <a href="?page=1">&laquo; first</a>
                   <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                   {% endif %}

                   <span class="current">
                       Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                   </span>

                   {% if page_obj.has_next %}
                   <a href="?page={{ page_obj.next_page_number }}">next</a>
                   <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                   {% endif %}
               </span>
           </div>
       </div>
   </div>

   {% endcomment %}

books/templates/teste.html
{% extends "base.html" %}
{% block content %}
<div class="container" style="max-width:800px">
    {% for book in books %}

    <p> {{book.title}} </p>

    {% endfor %}

</div>
{% endblock %}